namespace SistemaGian.Application.Models.WebManagement;

/// <summary>
/// Contrato único de claves de contenido publicables.
/// Cada clave debe existir en ViewModel + SaveSettings + vista pública + TitleFor.
/// </summary>
public static class WebSiteContentContract
{
    public static readonly IReadOnlyDictionary<string, string> Defaults = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // Layout
        ["seo.titleSuffix"] = "Materiales de construcción",
        ["seo.metaDescription"] = "AGS MAT — materiales de construcción para corralones, constructoras y desarrolladoras.",
        ["layout.topbarPrimary"] = "Materiales para corralones, constructoras y desarrolladoras",
        ["layout.topbarSecondary"] = "Sin pagos online: confirmás por WhatsApp",
        ["layout.searchPlaceholder"] = "Buscar materiales…",
        ["layout.searchButton"] = "Buscar",
        ["layout.cartLabel"] = "Carrito",

        // Home chrome
        ["home.searchPlaceholder"] = "Buscar cemento, ladrillos, hierros…",
        ["home.searchButton"] = "Buscar",
        ["home.chipsLabel"] = "Buscados",
        ["home.heroCtaCatalog"] = "Ver catálogo",
        ["home.heroCtaWhatsApp"] = "WhatsApp",
        ["home.heroCtaQuote"] = "Pedir presupuesto →",
        ["home.audienceLink"] = "Conocé cómo trabajamos →",
        ["home.metricShippingTitle"] = "Envíos y retiro",
        ["home.metricShippingText"] = "Coordinamos entrega en obra o retiro en el corralón",
        ["home.highlightOffersTitle"] = "Hay ofertas ahora",
        ["home.highlightOffersText"] = "Varios materiales con precio especial para reponer o arrancar la obra.",
        ["home.highlightOffersCta"] = "Ver ofertas",
        ["home.highlightCatalogTitle"] = "Lo que tu obra necesita",
        ["home.highlightCatalogText"] = "Cemento, ladrillos, hierros y más. Armá el pedido y lo cotizamos juntos.",
        ["home.highlightWhatsAppTitle"] = "Hablás con alguien de acá",
        ["home.highlightWhatsAppText"] = "Sin pagos online. Confirmás stock, cantidades y entrega por WhatsApp.",
        ["home.benefitsLink"] = "Cómo trabajamos →",
        ["home.offersRibbon"] = "Oportunidades",
        ["home.offersLink"] = "Ver todas las ofertas →",
        ["home.featuredKicker"] = "Catálogo",
        ["home.featuredLink"] = "Ver catálogo completo →",
        ["home.emptyTitle"] = "Todavía no hay productos publicados",
        ["home.emptyText"] = "Publicá productos desde el sistema de gestión y van a aparecer acá automáticamente.",
        ["home.stepsKicker"] = "Simple",
        ["home.stepsHelp"] = "¿Necesitás ayuda para armar el pedido?",
        ["home.stepsWhatsAppCta"] = "Escribinos por WhatsApp",
        ["home.stepsContactCta"] = "Pedir asesoramiento",
        ["home.ctaKicker"] = "Presupuesto sin cargo",
        ["home.ctaPrimary"] = "Pedir presupuesto",
        ["home.ctaSecondary"] = "Hablar con un asesor",
        ["home.ctaBullets"] = "Respondemos el mismo día hábil\nCotizamos por cantidad y logística\nEntrega en obra o retiro en el corralón",

        // Catalog page copy
        ["catalog.heroKicker"] = "Catálogo",
        ["catalog.heroTitle"] = "Materiales listos para presupuesto",
        ["catalog.heroText"] = "Recorré el surtido, filtrá por rubro y sumá al carrito. El pedido se confirma por WhatsApp.",
        ["catalog.introKicker"] = "Todo el surtido",
        ["catalog.introTitle"] = "Encontrá el material para tu próxima obra",
        ["catalog.introText"] = "Compará opciones, guardá productos en el carrito y pedí una cotización personalizada.",
        ["catalog.trustItems"] = "Precios claros\nAsesoramiento real\nPedido por WhatsApp",
        ["catalog.filtersHead"] = "Encontrá más rápido",
        ["catalog.filtersTitle"] = "Filtros",
        ["catalog.filterSearch"] = "Buscar",
        ["catalog.filterSearchPlaceholder"] = "Cemento, hierro, marca…",
        ["catalog.filterCategory"] = "Categoría",
        ["catalog.filterAllCategories"] = "Todas",
        ["catalog.filterOffersTitle"] = "Solo ofertas",
        ["catalog.filterOffersHint"] = "Mostrá precios rebajados",
        ["catalog.filterSubmit"] = "Ver resultados",
        ["catalog.filterClear"] = "Limpiar",
        ["catalog.filterHelp"] = "¿No encontrás algo? Pedinos cotización y te ayudamos.",
        ["catalog.emptyResults"] = "No encontramos productos con esos filtros.",
        ["catalog.sortLabel"] = "Ordenar por",
        ["catalog.introColor"] = "#FFFFFF",
        ["catalog.introTextColor"] = "#1D2430",
        ["catalog.filtersColor"] = "#FFFFFF",
        ["catalog.filtersTextColor"] = "#1D2430",

        // Product / card chrome
        ["card.addToCart"] = "Agregar al carrito",
        ["card.viewDetail"] = "Ver detalle",
        ["card.priceBefore"] = "Antes:",
        ["card.savingsPrefix"] = "Ahorrás",
        ["card.offerFallback"] = "OFERTA",
        ["card.badge3d"] = "3D",
        ["product.descriptionTitle"] = "Descripción",
        ["product.addToCart"] = "Agregar al carrito",
        ["product.quoteCta"] = "Pedir presupuesto",
        ["product.qtyLabel"] = "Cantidad",
        ["product.priceNote"] = "Precios estimados sujetos a confirmación de stock y logística.",
        ["product.benefits"] = "Coordinamos entrega en obra o retiro en depósito\nConfirmás el pedido por WhatsApp, sin pagos online\nAsesoramiento en cantidades y rendimiento",

        // About leftovers
        ["about.heroCtaCatalog"] = "Ver catálogo",
        ["about.heroCtaQuote"] = "Pedir presupuesto",
        ["about.statProductsLabel"] = "productos publicados",
        ["about.statCategoriesLabel"] = "categorías activas",
        ["about.statWhatsAppTitle"] = "WhatsApp",
        ["about.statWhatsAppText"] = "confirmación directa",
        ["about.heroColor"] = "#1F4F7A",
        ["about.heroTextColor"] = "#FFFFFF",
        ["about.storyColor"] = "#FFFFFF",
        ["about.storyTextColor"] = "#1D2430",
        ["about.mvColor"] = "#F6F7F9",
        ["about.mvTextColor"] = "#1D2430",
        ["about.pillarsColor"] = "#FFFFFF",
        ["about.pillarsTextColor"] = "#1D2430",
        ["about.catsColor"] = "#FFFFFF",
        ["about.catsTextColor"] = "#1D2430",
        ["about.policyColor"] = "#FFFFFF",
        ["about.policyTextColor"] = "#1D2430",
        ["about.ctaColor"] = "#1F4F7A",
        ["about.ctaTextColor"] = "#FFFFFF",

        // Contact
        ["contact.title"] = "Solicitar presupuesto",
        ["contact.lead"] = "Contanos qué necesitás. Guardamos la consulta y te armamos el mensaje de WhatsApp.",
        ["contact.labelName"] = "Nombre",
        ["contact.labelCompany"] = "Empresa",
        ["contact.labelPhone"] = "Teléfono",
        ["contact.labelEmail"] = "Email",
        ["contact.labelCustomerType"] = "Tipo de cliente",
        ["contact.labelMessage"] = "¿Qué materiales necesitás?",
        ["contact.messagePlaceholder"] = "Ej: 4 pallets hueco 12, 40 bolsas cemento, arena para contrapiso...",
        ["contact.submit"] = "Armar consulta WhatsApp",
        ["contact.sentTitle"] = "Consulta lista para enviar",
        ["contact.sentOpenWhatsApp"] = "Abrir WhatsApp",
        ["contact.pageColor"] = "#F5F8FB",
        ["contact.pageTextColor"] = "#1D2430",

        // Cart / checkout
        ["cart.kicker"] = "Pedido en preparación",
        ["cart.title"] = "Tu carrito de materiales",
        ["cart.lead"] = "Revisá las cantidades. El pedido se confirma con una persona por WhatsApp.",
        ["cart.emptyTitle"] = "Tu carrito está esperando materiales",
        ["cart.emptyText"] = "Recorré el catálogo y armá el pedido para tu obra.",
        ["cart.emptyCta"] = "Explorar catálogo",
        ["cart.continueShopping"] = "← Seguir agregando productos",
        ["cart.summaryTitle"] = "Resumen del pedido",
        ["cart.summaryBadge"] = "Sin pago online",
        ["cart.summaryNote"] = "El total y la entrega se confirman con un asesor según stock y logística.",
        ["cart.checkoutCta"] = "Continuar por WhatsApp",
        ["cart.safeItems"] = "Cotización personalizada\nEntrega o retiro coordinado",
        ["checkout.title"] = "Enviar pedido",
        ["checkout.lead"] = "Completá tus datos. Armamos el texto y abrimos WhatsApp para que lo envíes.",
        ["checkout.submit"] = "Armar mensaje y abrir WhatsApp",
        ["checkout.sentTitle"] = "Pedido listo para enviar",
        ["checkout.sentLead"] = "Revisá el mensaje y tocá el botón para abrirlo en WhatsApp. Vos lo enviás desde tu celular o PC.",
        ["checkout.sentOpenWhatsApp"] = "Abrir WhatsApp y enviar",
        ["checkout.sentContinue"] = "Seguir comprando",
        ["cart.pageColor"] = "#FFFFFF",
        ["cart.pageTextColor"] = "#1D2430",
    };

    public static string Get(string key, string? fallback = null) =>
        Defaults.TryGetValue(key, out var value) ? value : (fallback ?? key);

    /// <summary>Propiedades del ViewModel ↔ claves de configuración (campos nuevos del contrato).</summary>
    public static readonly (string Property, string Key)[] ViewModelBindings =
    [
        ("SeoTitleSuffix", "seo.titleSuffix"),
        ("SeoMetaDescription", "seo.metaDescription"),
        ("TopbarPrimary", "layout.topbarPrimary"),
        ("TopbarSecondary", "layout.topbarSecondary"),
        ("SearchPlaceholder", "layout.searchPlaceholder"),
        ("SearchButton", "layout.searchButton"),
        ("CartLabel", "layout.cartLabel"),
        ("HomeSearchPlaceholder", "home.searchPlaceholder"),
        ("HomeSearchButton", "home.searchButton"),
        ("HomeChipsLabel", "home.chipsLabel"),
        ("HomeHeroCtaCatalog", "home.heroCtaCatalog"),
        ("HomeHeroCtaWhatsApp", "home.heroCtaWhatsApp"),
        ("HomeHeroCtaQuote", "home.heroCtaQuote"),
        ("HomeAudienceLink", "home.audienceLink"),
        ("HomeMetricShippingTitle", "home.metricShippingTitle"),
        ("HomeMetricShippingText", "home.metricShippingText"),
        ("HomeHighlightOffersTitle", "home.highlightOffersTitle"),
        ("HomeHighlightOffersText", "home.highlightOffersText"),
        ("HomeHighlightOffersCta", "home.highlightOffersCta"),
        ("HomeHighlightCatalogTitle", "home.highlightCatalogTitle"),
        ("HomeHighlightCatalogText", "home.highlightCatalogText"),
        ("HomeHighlightWhatsAppTitle", "home.highlightWhatsAppTitle"),
        ("HomeHighlightWhatsAppText", "home.highlightWhatsAppText"),
        ("HomeBenefitsLink", "home.benefitsLink"),
        ("HomeOffersRibbon", "home.offersRibbon"),
        ("HomeOffersLink", "home.offersLink"),
        ("HomeFeaturedKicker", "home.featuredKicker"),
        ("HomeFeaturedLink", "home.featuredLink"),
        ("HomeEmptyTitle", "home.emptyTitle"),
        ("HomeEmptyText", "home.emptyText"),
        ("HomeStepsKicker", "home.stepsKicker"),
        ("HomeStepsHelp", "home.stepsHelp"),
        ("HomeStepsWhatsAppCta", "home.stepsWhatsAppCta"),
        ("HomeStepsContactCta", "home.stepsContactCta"),
        ("HomeCtaKicker", "home.ctaKicker"),
        ("HomeCtaPrimary", "home.ctaPrimary"),
        ("HomeCtaSecondary", "home.ctaSecondary"),
        ("HomeCtaBullets", "home.ctaBullets"),
        ("CatalogHeroKicker", "catalog.heroKicker"),
        ("CatalogHeroTitle", "catalog.heroTitle"),
        ("CatalogHeroText", "catalog.heroText"),
        ("CatalogIntroKicker", "catalog.introKicker"),
        ("CatalogIntroTitle", "catalog.introTitle"),
        ("CatalogIntroText", "catalog.introText"),
        ("CatalogTrustItems", "catalog.trustItems"),
        ("CatalogFiltersHead", "catalog.filtersHead"),
        ("CatalogFiltersTitle", "catalog.filtersTitle"),
        ("CatalogFilterSearch", "catalog.filterSearch"),
        ("CatalogFilterSearchPlaceholder", "catalog.filterSearchPlaceholder"),
        ("CatalogFilterCategory", "catalog.filterCategory"),
        ("CatalogFilterAllCategories", "catalog.filterAllCategories"),
        ("CatalogFilterOffersTitle", "catalog.filterOffersTitle"),
        ("CatalogFilterOffersHint", "catalog.filterOffersHint"),
        ("CatalogFilterSubmit", "catalog.filterSubmit"),
        ("CatalogFilterClear", "catalog.filterClear"),
        ("CatalogFilterHelp", "catalog.filterHelp"),
        ("CatalogEmptyResults", "catalog.emptyResults"),
        ("CatalogSortLabel", "catalog.sortLabel"),
        ("CatalogIntroColor", "catalog.introColor"),
        ("CatalogIntroTextColor", "catalog.introTextColor"),
        ("CatalogFiltersColor", "catalog.filtersColor"),
        ("CatalogFiltersTextColor", "catalog.filtersTextColor"),
        ("CardAddToCart", "card.addToCart"),
        ("CardViewDetail", "card.viewDetail"),
        ("CardPriceBefore", "card.priceBefore"),
        ("CardSavingsPrefix", "card.savingsPrefix"),
        ("CardOfferFallback", "card.offerFallback"),
        ("CardBadge3d", "card.badge3d"),
        ("ProductDescriptionTitle", "product.descriptionTitle"),
        ("ProductAddToCart", "product.addToCart"),
        ("ProductQuoteCta", "product.quoteCta"),
        ("ProductQtyLabel", "product.qtyLabel"),
        ("ProductPriceNote", "product.priceNote"),
        ("ProductBenefits", "product.benefits"),
        ("AboutHeroCtaCatalog", "about.heroCtaCatalog"),
        ("AboutHeroCtaQuote", "about.heroCtaQuote"),
        ("AboutStatProductsLabel", "about.statProductsLabel"),
        ("AboutStatCategoriesLabel", "about.statCategoriesLabel"),
        ("AboutStatWhatsAppTitle", "about.statWhatsAppTitle"),
        ("AboutStatWhatsAppText", "about.statWhatsAppText"),
        ("AboutHeroColor", "about.heroColor"),
        ("AboutHeroTextColor", "about.heroTextColor"),
        ("AboutStoryColor", "about.storyColor"),
        ("AboutStoryTextColor", "about.storyTextColor"),
        ("AboutMvColor", "about.mvColor"),
        ("AboutMvTextColor", "about.mvTextColor"),
        ("AboutPillarsColor", "about.pillarsColor"),
        ("AboutPillarsTextColor", "about.pillarsTextColor"),
        ("AboutCatsColor", "about.catsColor"),
        ("AboutCatsTextColor", "about.catsTextColor"),
        ("AboutPolicyColor", "about.policyColor"),
        ("AboutPolicyTextColor", "about.policyTextColor"),
        ("AboutCtaBlockColor", "about.ctaColor"),
        ("AboutCtaBlockTextColor", "about.ctaTextColor"),
        ("ContactTitle", "contact.title"),
        ("ContactLead", "contact.lead"),
        ("ContactLabelName", "contact.labelName"),
        ("ContactLabelCompany", "contact.labelCompany"),
        ("ContactLabelPhone", "contact.labelPhone"),
        ("ContactLabelEmail", "contact.labelEmail"),
        ("ContactLabelCustomerType", "contact.labelCustomerType"),
        ("ContactLabelMessage", "contact.labelMessage"),
        ("ContactMessagePlaceholder", "contact.messagePlaceholder"),
        ("ContactSubmit", "contact.submit"),
        ("ContactSentTitle", "contact.sentTitle"),
        ("ContactSentOpenWhatsApp", "contact.sentOpenWhatsApp"),
        ("ContactPageColor", "contact.pageColor"),
        ("ContactPageTextColor", "contact.pageTextColor"),
        ("CartKicker", "cart.kicker"),
        ("CartTitle", "cart.title"),
        ("CartLead", "cart.lead"),
        ("CartEmptyTitle", "cart.emptyTitle"),
        ("CartEmptyText", "cart.emptyText"),
        ("CartEmptyCta", "cart.emptyCta"),
        ("CartContinueShopping", "cart.continueShopping"),
        ("CartSummaryTitle", "cart.summaryTitle"),
        ("CartSummaryBadge", "cart.summaryBadge"),
        ("CartSummaryNote", "cart.summaryNote"),
        ("CartCheckoutCta", "cart.checkoutCta"),
        ("CartSafeItems", "cart.safeItems"),
        ("CheckoutTitle", "checkout.title"),
        ("CheckoutLead", "checkout.lead"),
        ("CheckoutSubmit", "checkout.submit"),
        ("CheckoutSentTitle", "checkout.sentTitle"),
        ("CheckoutSentLead", "checkout.sentLead"),
        ("CheckoutSentOpenWhatsApp", "checkout.sentOpenWhatsApp"),
        ("CheckoutSentContinue", "checkout.sentContinue"),
        ("CartPageColor", "cart.pageColor"),
        ("CartPageTextColor", "cart.pageTextColor")
    ];

    public static void ApplyToViewModel(WebManagementViewModel model, Func<string, string, string> getSetting)
    {
        var type = typeof(WebManagementViewModel);
        foreach (var (property, key) in ViewModelBindings)
        {
            var pi = type.GetProperty(property);
            if (pi is null || !pi.CanWrite) continue;
            pi.SetValue(model, getSetting(key, Get(key)));
        }
    }

    public static IEnumerable<(string Key, string? Value)> ReadFromViewModel(WebManagementViewModel model)
    {
        var type = typeof(WebManagementViewModel);
        foreach (var (property, key) in ViewModelBindings)
        {
            var pi = type.GetProperty(property);
            yield return (key, pi?.GetValue(model) as string);
        }
    }
}
